# Generated by Django 5.1.7 on 2025-04-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_cart_user_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='visiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.visiteur'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
