# Generated by Django 5.1.7 on 2025-04-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_cart_visiteur_alter_cart_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='visiteur',
        ),
    ]
