# Generated by Django 5.1.7 on 2025-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='carte_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='carte_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='carte_numero',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('VIR', 'Virement')], default='Carte bancaire', max_length=50),
        ),
    ]
