# Generated by Django 5.1.7 on 2025-04-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_paiement_carte_cvv_paiement_carte_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='visiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.visiteur'),
        ),
    ]
