# Generated by Django 5.1.7 on 2025-05-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_alter_client_id'),
        ('shop_app', '0009_wishlist'),
    ]

    operations = [
    ]
