# Generated by Django 5.1.7 on 2025-05-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_merge_0008_alter_client_id_0009_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='client',
        ),
    ]
