# Generated by Django 5.1.7 on 2025-05-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_rename_user_cart_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='client',
            new_name='user',
        ),
    ]
